spring.application.name=plufinder_backend

###DATABASE URL ADDRESS(to find "products_inDatabase")###
spring.datasource.url=jdbc:mysql://localhost:3306/grocerystoreproduction?useSSL=false&allowPublicKeyRetrieval=true

###DATABASE LOGIN CREDENTIALS###
spring.datasource.username=root
spring.datasource.password=root

###HIBERNATE PROPERTIES###
##Defines compatible SQL style for the database kind used here("MySQL8").
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
##Defines how database table scheme will be modified upon every startup/shutdown/update/etc.  
spring.jpa.hibernate.ddl-auto=update