spring.application.name=plufinder_backend

########LOCALHOST DB########
###DATABASE URL ADDRESS(to find "products_inDatabase")###
spring.datasource.url=jdbc:mysql://localhost:3306/grocerystoreproduction?useSSL=false&allowPublicKeyRetrieval=true
###DATABASE LOGIN CREDENTIALS###
spring.datasource.username=root
spring.datasource.password=root

########AWS RDS########
# spring.datasource.url=jdbc:mysql://plufinder-rds.cd6k0oe2m1wg.us-east-2.rds.amazonaws.com:3306/grocerystoreproduction?useSSL=false&allowPublicKeyRetrieval=true&connectTimeout=30000&socketTimeout=30000
# spring.datasource.username=admin
# spring.datasource.password=admin-root-

###HIBERNATE PROPERTIES###
##Defines compatible SQL style for the database type used("MySQL" in this case).
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
#spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
##Defines how database table scheme will be modified upon every startup/shutdown/update/etc.  
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.devtools.livereload.enabled=true

###FOR DEBUGGING(Just in case)###
#logging.level.org.springframework=DEBUG
#logging.level.com.fcpt.plufinder=DEBUG


